# Generated by Django 3.2.7 on 2023-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avartar',
            new_name='avatar',
        ),
    ]
