# Generated by Django 3.2.7 on 2023-12-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_avartar_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, default='10', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.avatar'),
        ),
    ]
